		ORG 	0000H
MAIN: 	MOV 	A,#0FEH
OUTPUT: MOV 	P1,A
		RL		A
		LCALL	DELAY
		SJMP 	OUTPUT
		
DELAY: 	MOV 	R6,#0		 ;—” ±≥Ã–Ú,‘º125∫¡√Î
DELOOP2:MOV 	R7,#250
DELOOP1:DJNZ 	R7,DELOOP1
		DJNZ 	R6,DELOOP2
		RET
		END